// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSpjxAtbvGflmokjgZiuGk6xgrvwVR9XU',
    appId: '1:671369834198:web:951b7c0225431149a16377',
    messagingSenderId: '671369834198',
    projectId: 'expenditure-tracker-faa32',
    authDomain: 'expenditure-tracker-faa32.firebaseapp.com',
    storageBucket: 'expenditure-tracker-faa32.appspot.com',
    measurementId: 'G-QL9SZLX1LQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdqYTq99L6jks-aKSkLhw0PN7SVtyqhrU',
    appId: '1:671369834198:android:bf174bb1829cd03fa16377',
    messagingSenderId: '671369834198',
    projectId: 'expenditure-tracker-faa32',
    storageBucket: 'expenditure-tracker-faa32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPabAlZKhLnbDeXturgSGV596gTO7qwGU',
    appId: '1:671369834198:ios:d8f0010cb6eab6eea16377',
    messagingSenderId: '671369834198',
    projectId: 'expenditure-tracker-faa32',
    storageBucket: 'expenditure-tracker-faa32.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPabAlZKhLnbDeXturgSGV596gTO7qwGU',
    appId: '1:671369834198:ios:d8f0010cb6eab6eea16377',
    messagingSenderId: '671369834198',
    projectId: 'expenditure-tracker-faa32',
    storageBucket: 'expenditure-tracker-faa32.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSpjxAtbvGflmokjgZiuGk6xgrvwVR9XU',
    appId: '1:671369834198:web:fb9e42c094091443a16377',
    messagingSenderId: '671369834198',
    projectId: 'expenditure-tracker-faa32',
    authDomain: 'expenditure-tracker-faa32.firebaseapp.com',
    storageBucket: 'expenditure-tracker-faa32.appspot.com',
    measurementId: 'G-KXEJZDN012',
  );
}
